#:kivy 1.0.9
<Widgets>:

<PongBall>:
    size: 50, 50
    canvas:
        Color:
            rgba:0,1,0,1
        Ellipse:
            pos: self.pos
            size: self.size

<PongPaddle>:
    size: 25, 200
    canvas:
        Color:
            rgba:1,1,0,1
        Rectangle:
            pos:self.pos
            size:self.size
<background>
    image_one: image_one
    Image:
        id: image_one
        source: "Comp130KivyApp/green.jpg"
        pos: self.pos
        size:800,800
<PongGame>:
    ball: pong_ball
    player1: player_left
    player2: player_right


    canvas:
        Color:
            rgba:1,1,0,1
        Rectangle:
            pos: self.center_x - 400, 0
            size: 400, self.height




    Label:
        font_size: 70
        center_x: root.width / 4
        top: root.top - 50

        text: str(root.player1.insectLives)

    Label:
        font_size: 70
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: str(root.player2.lives)

    PongBall:

        id: pong_ball
        center: self.parent.center

    PongPaddle:
        id: player_left


    PongPaddle:
        id: player_right
        x: root.width-self.width
        center_y: root.center_y